/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yundaW16setting_cn_MyNative */

#ifndef _Included_com_yundaW16setting_cn_MyNative
#define _Included_com_yundaW16setting_cn_MyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yundaW16setting_cn_MyNative
 * Method:    CheckBarcode
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_yundaW16setting_cn_MyNative_CheckBarcode
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_yundaW16setting_cn_MyNative
 * Method:    cutCode
 * Signature: ([BILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yundaW16setting_cn_MyNative_cutCode
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
